version: "3"

services:
  client-demo:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: client-demo
    ports:
      - "3003:3003"
    volumes:
      - ./ngnix.conf:/etc/nginx/conf.d/default.conf
